# Generated by Django 2.2.3 on 2019-09-24 01:07

import app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190920_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('unknown', 0), ('buy', 1), ('sell', 2), ('interest', 3), ('dividend', 4), ('fee', 5), ('transfer', 6)], default=0, max_length=20),
        ),
    ]
