# Generated by Django 2.2.3 on 2019-09-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190924_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
