# Generated by Django 2.2.3 on 2019-09-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190924_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashmovement',
            old_name='ledger_id',
            new_name='unique',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='unique',
        ),
    ]
