# Generated by Django 2.2.3 on 2019-09-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190925_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='unique',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unique',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
