# Generated by Django 2.2.6 on 2019-10-29 07:31

import app.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190925_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 0), ('future', 1), ('fund', 2), ('cash', 3), ('fx_spot', 4), ('cash_equity', 5), ('fx_forward', 6)], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 0), ('future', 1), ('fund', 2), ('cash', 3), ('fx_spot', 4), ('cash_equity', 5), ('fx_forward', 6)], default=0, max_length=20),
        ),
    ]
