# Generated by Django 2.2.6 on 2019-11-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_position'),
        ('app', '0007_auto_20191029_0731'),
    ]

    operations = [
    ]
