# Generated by Django 2.2.6 on 2019-11-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20191105_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='custodian',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Reyl', 'Reyl'), ('Exante', 'Exante'), ('UBS', 'UBS'), ('Selftrade', 'Selftrade'), ('Interactive Brokers', 'Interactive Brokers')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='group',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Shiny', 'Shiny'), ('Aviva', 'Aviva'), ('MFT', 'MFT')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='owner',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Shiny', 'Shiny'), ('Alex', 'Alex'), ('Ed', 'Ed'), ('Mid Pacific AM', 'Mid Pacific AM')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='custodian',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Reyl', 'Reyl'), ('Exante', 'Exante'), ('UBS', 'UBS'), ('Selftrade', 'Selftrade'), ('Interactive Brokers', 'Interactive Brokers')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='group',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Shiny', 'Shiny'), ('Aviva', 'Aviva'), ('MFT', 'MFT')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='owner',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Shiny', 'Shiny'), ('Alex', 'Alex'), ('Ed', 'Ed'), ('Mid Pacific AM', 'Mid Pacific AM')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='resolution',
            field=models.CharField(choices=[('unknown', 'unknown'), ('1s', '1s'), ('1m', '1m'), ('1h', '1h'), ('1d', '1d')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Bloomberg', 'Bloomberg'), ('Exante', 'Exante'), ('Reyl', 'Reyl'), ('Ft', 'Ft')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='custodian',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Reyl', 'Reyl'), ('Exante', 'Exante'), ('UBS', 'UBS'), ('Selftrade', 'Selftrade'), ('Interactive Brokers', 'Interactive Brokers')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='group',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Shiny', 'Shiny'), ('Aviva', 'Aviva'), ('MFT', 'MFT')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Shiny', 'Shiny'), ('Alex', 'Alex'), ('Ed', 'Ed'), ('Mid Pacific AM', 'Mid Pacific AM')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('buy', 'buy'), ('sell', 'sell'), ('interest', 'interest'), ('dividend', 'dividend'), ('fee', 'fee'), ('transfer', 'transfer')], default='unknown', max_length=20),
        ),
    ]
