# Generated by Django 2.2.6 on 2019-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191108_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future')], default='unknown', max_length=20),
        ),
    ]
