# Generated by Django 2.2.6 on 2019-11-22 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191122_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='as_of',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 0, 0)),
            preserve_default=False,
        ),
    ]
