# Generated by Django 2.2.6 on 2020-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_price_as_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='aspect',
            field=models.CharField(choices=[('close', 'close'), ('open', 'open'), ('high', 'high'), ('low', 'low'), ('volume', 'volume')], default='close', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future'), ('index', 'index')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future'), ('index', 'index')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='resolution',
            field=models.CharField(choices=[('unknown', 'unknown'), ('1s', '1s'), ('1m', '1m'), ('1h', '1h'), ('1d', '1d'), ('5m', '5m')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Bloomberg', 'Bloomberg'), ('Exante', 'Exante'), ('Reyl', 'Reyl'), ('Ft', 'Ft'), ('PortaraCQG', 'PortaraCQG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('future', 'future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future'), ('index', 'index')], default='unknown', max_length=20),
        ),
    ]
