# Generated by Django 2.2.6 on 2020-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200423_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('trade', 'trade'), ('bid', 'bid'), ('ask', 'ask'), ('nav', 'nav')], default='unknown', max_length=20),
        ),
    ]
