# Generated by Django 2.2.6 on 2020-06-01 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200602_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='aspect',
            field=models.CharField(choices=[('close', 'close'), ('open', 'open'), ('high', 'high'), ('low', 'low'), ('volume', 'volume')], db_index=True, default='close', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('trade', 'trade'), ('bid', 'bid'), ('ask', 'ask'), ('nav', 'nav')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='resolution',
            field=models.CharField(choices=[('unknown', 'unknown'), ('1s', '1s'), ('1m', '1m'), ('1h', '1h'), ('1d', '1d'), ('5m', '5m')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='symbol',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='price',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
