# Generated by Django 2.2.6 on 2020-06-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_fundclassification_as_of'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='unique_cash_movement',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction',
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(fields=('custodian', 'owner', 'group', 'transaction_date', 'value_date', 'currency', 'description'), name='unique_cash_movement'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('custodian', 'owner', 'group', 'transaction_time', 'value_date', 'symbol', 'currency', 'transaction_type', 'asset_type'), name='unique_transaction'),
        ),
    ]
