# Generated by Django 2.2.6 on 2020-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_fundclassification_as_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('trade', 'trade'), ('bid', 'bid'), ('ask', 'ask'), ('nav', 'nav'), ('mid', 'mid')], db_index=True, default='unknown', max_length=20),
        ),
    ]
