# Generated by Django 2.2.6 on 2020-06-05 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200605_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(null=True)),
                ('bb_ticker', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('unknown', 'unknown'), ('index_future', 'index_future'), ('fund', 'fund'), ('cash', 'cash'), ('fx_spot', 'fx_spot'), ('cash_equity', 'cash_equity'), ('fx_forward', 'fx_forward'), ('fx_future', 'fx_future'), ('equity_index', 'equity_index'), ('volatility_index', 'volatility_index')], default='unknown', max_length=20)),
                ('contract_mul', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=20)),
                ('underlying_index', models.CharField(max_length=20, null=True)),
                ('isin', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(db_index=True, max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('fund_size', models.FloatField(null=True)),
                ('fund_size_currency', models.CharField(max_length=20, null=True)),
                ('front_load', models.FloatField(null=True)),
                ('back_load', models.FloatField(null=True)),
                ('min_investment', models.FloatField(null=True)),
                ('performance_fee', models.FloatField(null=True)),
                ('geo', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
