# Generated by Django 2.2.6 on 2020-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_universe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='universe',
            constraint=models.UniqueConstraint(fields=('symbol', 'bb_ticker', 'expiry_date', 'asset_type', 'contract_mul', 'currency', 'underlying_index', 'isin', 'name', 'fund_size', 'fund_size_currency', 'front_load', 'back_load', 'min_investment', 'performance_fee', 'geo'), name='unique_universe'),
        ),
    ]
