# Generated by Django 2.2.6 on 2020-06-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200608_2335'),
        ('app', '0022_auto_20200608_1641'),
    ]

    operations = [
    ]
