# Generated by Django 2.2.6 on 2020-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_merge_20200612_1014'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universe',
            name='unique_universe',
        ),
        migrations.AddConstraint(
            model_name='universe',
            constraint=models.UniqueConstraint(fields=('symbol', 'as_of'), name='unique_universe'),
        ),
    ]
